client_config_backend: settings
client_config:
  client_id: "772442866169-a9503q9317koip9qr3hjkn9kr9sgvdps.apps.googleusercontent.com"
  client_secret: "qsfKNtvuBaaxJYr_tDnia19C"

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
