# Generated by Django 3.1.2 on 2020-10-03 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mmp_app', '0003_auto_20201003_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='courses',
        ),
        migrations.AddField(
            model_name='faculty',
            name='courses',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='mmp_app.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
